-- Create product_images table to support multiple images per product
create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  id integer not null references public.products(id) on delete cascade,
  image_url text not null,
  created_at timestamp with time zone default now()
);

create index if not exists idx_product_images_product_id on public.product_images(id);


