// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaxmkgylkaeasjufhlnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFheG1rZ3lsa2FlYXNqdWZobG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTg2ODgsImV4cCI6MjA3MjczNDY4OH0.tNCVWaUkGScPpGGvimy7ZO4kK4Zkl9gZWuGpxgz78Ao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});